[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Proxy /api/* to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback (Vite/React)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
